### ISSUE TITLE
Bug fix: parse durations with hyphens

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/lingua-franca#12]
Some STT providers return duration phrases with hyphens eg "30-seconds" instead of the usual "30 seconds". The existing `extract_duration` implementation does not seem to handle this.

Example tests:
```
self.assertEqual(extract_duration("it went for 30-seconds"), (30, "it went for"))
self.assertEqual(extract_duration("this will last for 30-minutes"), (1800, "this will last for"))
```

**Comment by vegerot** [comment]
See #14

**Comment by JarbasAl** [comment]
fixed by https://github.com/MycroftAI/lingua-franca/pull/40
