### ISSUE TITLE
Resolving files fails unless langcode case matches

### ISSUE THREAD

**Issue by forslund** [MycroftAI/lingua-franca#120]
I found the following when trying to wrap my head around https://github.com/MycroftAI/mycroft-timer/pull/77

```
>>> from lingua_franca.lang import set_active_lang
>>> set_active_lang('de-de')
>>> dur = timedelta(2)
>>> dur
datetime.timedelta(2)
>>> nice_duration(dur)
'zwei Tage '
>>> set_active_lang('de-DE')
>>> nice_duration(dur)
'zwei days '
```

The stt uses the lang code with uppercase second part (de-DE) and this get's reported to the intent service which sets the active language using that. This results in that the [_translate_word](https://github.com/MycroftAI/lingua-franca/blob/master/lingua_franca/format.py#L56) function fails to find a translation and returns the untranslated word.

We could
- Always lowercase on the lang when running translate word
- Always converting the active lang string to lowercase 
or
- Disallow lang codes using uppercase

Things like `pronounce_number()` handles this format so the solution should probably not be the third one. Making the active_lang always be lowercase (i.e. running .lower() on the input when setting) should be fairly safe and general, the downside being that if we want to in the future differentiate between uppercased lang-codes and lowercased lang-codes we might create a whole lot of bugs since code is relying on the fact that this should always be lowercase...

Any preferences to which solution is the better one?

@ChanceNCounter did you do anything with this in your refactor (since you did a whole lot with active lang)

For the time being I posted a PR in core making sure the lang code was sent as lowercase when setting the active language code.

**Comment by ChanceNCounter** [comment]
Indeed, I do think this is fixed in the refactor, but I'll have to add explicit unit tests to make sure (checking PRs from a toaster where I can't test =P) My solution was to always lowercase the input when a lang code is selected. I have absolutely no opinion on whether that's the best solution.

At a glance, there are `.lower()` calls in the lang code getters and setters, now located in the tentatively-named `common.py`.

**Comment by forslund** [comment]
Good, then we'll wait for the merge of your PR to tackle this.
