### ISSUE TITLE
bug - extract datetime lowercases remainder

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/lingua-franca#147]
the remainder text should not be lowercased, this impacts comparisons between remainder and original utterance

similar to #145 which has been fixed in #146 

will fix this in the datetime rewrite #74

**Comment by ChanceNCounter** [comment]
I think this can be addressed without much of a performance hit by way of rolling token replacement. The alternative, iterating over the original and replacing only the chunks where `this_chunk != original.lower()`, obviously doesn't scale well to large inputs.
