### ISSUE TITLE
better ordinals handling

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/lingua-franca#153]
when working on #135 i realized we need better control over ordinals flag

- first is non ambiguous 
- second can be the time unit, not a number
- third and above can be a fraction
- things like "half" should not be normalized either, but parsed by extract_number

the same distinction might be useful for extract_number, therefore i propose

ordinals=True -> consider edge cases an integer
ordinals=False -> consider edge cases a fraction
ordinals=None -> ignore ambiguous words

things like 1st, 2nd, 3rd, 4th... are explicit numbers and should always be extracted

things like "whole", "half" or other spoken language quirks should also be optional

**Comment by krisgesling** [comment]
I think the examples made it a bit clearer for me: 
```python
extract_number("i want the third option", ordinals=True) # returns 3
extract_number("i want the third option", ordinals=False) # returns 1/3
extract_number("i want the third option", ordinals=None) # returns None
```
So presumably ignore should only be used in very specific cases where you know you want neither fractions nor ordinals.

**Comment by JarbasAl** [comment]
yes exactly, the specific use case here is in the normalize() method, which would break downstream parsers that might want either of the options
