### ISSUE TITLE
One more "is" with literal found in format_cs.py:296

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/lingua-franca#169]
Good catch, @j1nx!

**Comment by Tony763** [comment]
![image](https://user-images.githubusercontent.com/5598750/102933193-1a34f100-44a2-11eb-863f-bce458af395d.png)
![image](https://user-images.githubusercontent.com/5598750/102933234-3042b180-44a2-11eb-8194-b9d9085ea036.png)

What is problem? `is` was already changed to `==`

**Comment by ChanceNCounter** [comment]
Maybe he's running an outdated version. Idk, I threw this up here because I don't have the lib on this computer =P I'll go see.

**Comment by Tony763** [comment]
Ok, let me know if anything needed.

**Comment by ChanceNCounter** [comment]
Yeap. Outdated. Thanks, @Tony763
