### ISSUE TITLE
CI seems to be pointing to another project

### ISSUE THREAD

**Issue by antoniomaciej** [MycroftAI/lingua-franca#18]
Hello, the badges for Travis CI and coverage in the Readme are pointing to another build (mycroft-core).

Is this intended? Is CI configured for this project? If I make a PR, would a build be triggered in Travis?

**Comment by krisgesling** [comment]
I don't believe there's any CI on this repo yet, we extracted it out of core relatively recently on request from the Community so currently changes made here aren't automatically pulled into core. This is something we were hoping to implement for the 19.08 release, which is imminent...

**Comment by antoniomaciej** [comment]
Ok, thank you for the clarification. Then I guess this is not really an issue. I'll just close it then :)
