### ISSUE TITLE
Wrong interpretation as fractions

### ISSUE THREAD

**Issue by Nithin-Holla** [MycroftAI/lingua-franca#205]
**Describe the bug**
For inputs such as 'eighteenth` and `twentieth` as in centuries, the input is wrongly interpreted as fractions and the output is a decimal number for instance 0.05555 (1/18) and 0.05 (1/20) respectively. This is incorrect.

**To Reproduce**
```python
import lingua_franca
from lingua_franca.parse import extract_number
lingua_franca.load_language('en')
print(extract_number('eighteenth'))
print(extract_number('twentieth'))
```

**Expected behavior**
The output could be `False` if it can't be converted to `18th` and `20th` for example.

**Environment (please complete the following information):**
 - Device type: Desktop
 - OS: MacOS
 - lingua-franca version: 0.4.2

**Comment by krisgesling** [comment]
Hi Nithin,

If you use the `ordinals` argument, this will return the correct number. Try this:
```python
print(extract_number('eighteenth', ordinals=True))
print(extract_number('twentieth', ordinals=True))
```

Would that meet your needs?

**Comment by Nithin-Holla** [comment]
Ah, wasn't aware of this argument. It's fine then!
