### ISSUE TITLE
"In 2007" should be parsed as year

### ISSUE THREAD

**Issue by slavaGanzin** [MycroftAI/lingua-franca#224]
**Describe the bug**
I know for Mycroft it reasonable to parse 2007 as 20:07. But this is a separate library, and for 2007 should be a year.

**To Reproduce**
```python
from lingua_franca.parse import *
lingua_franca.load_language('en')
print(lingua_franca.parse.extract_datetime('in 2007'))
[datetime.datetime(2022, 2, 21, 20, 7), '']
```

**Expected behavior**
[datetime.datetime(2007, 0, 0, 0, 0), '']

**env**
lingua_franca-0.4.2-py3-none-any.whl
python3.9

**Comment by slavaGanzin** [comment]
@JarbasAI Nice!

**Comment by krisgesling** [comment]
Thanks Jarbas - looks good!
