### ISSUE TITLE
python-dateutil version strong dependency

### ISSUE THREAD

**Issue by NeonBohdan** [MycroftAI/lingua-franca#227]
As You can see in [requirements](https://github.com/MycroftAI/lingua-franca/blob/master/requirements.txt) the is a strong version dependency of `python-dateutil==2.6.0`
It limits to use [lingua-franca](https://github.com/MycroftAI/lingua-franca) is one environment with `pandas, matplotlib` and so on

So it will be very usefull to extend support to at least `python-dateutil==2.7.3`

**Comment by krisgesling** [comment]
Hey Bohdan, thanks for flagging this - seems like a softer version requirement is a good move here.
