### ISSUE TITLE
PR # #2342 - add default value to nice_number param

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/lingua-franca#25]
while lingua franca is not adopted in mycroft-core some bug fixes and functionality are being pushed there

https://github.com/MycroftAI/mycroft-core/pull/2342

Add default value to parameter in nice_number & convert_mixed_fraction

Add tests for convert_mixed_fraction
Description

Docstrings for nice_number() and convert_to_mixed_fraction indicate that their denominators parameter should have a default value, but it didn't. convert_to_mixed_fraction also lacked tests.

**Comment by ChanceNCounter** [comment]
Most of this was handled in 120b94abae081625d803e11407a888877e75b018, but it appears that nl and sv were missed.
