### ISSUE TITLE
PR#2347 Fix extractnumber_es, add extract_numbers_es

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/lingua-franca#30]
https://github.com/MycroftAI/mycroft-core/pull/2347

- Fix bug causing extractnumber_es to return a sum instead of a list
- Add Spanish parser to extract_numbers and extract_number

**Comment by ChanceNCounter** [comment]
I can submit these directly after core takes them, if that'd make your part easier.

**Comment by ChanceNCounter** [comment]
(or you could pull core, I'm assuming that's been the drill)

**Comment by JarbasAl** [comment]
i'm mostly documenting it so it isn't forgotten, it would be great if you could resubmit the changes here! thank you

i know this is a bit bothersome, but it's temporary until lingua_franca is officially adopted by core
