### ISSUE TITLE
Parsing ordinals in form '7th' fails

### ISSUE THREAD

**Issue by krisgesling** [MycroftAI/lingua-franca#6]
Some STT providers return ordinals in the form of digit + suffix eg "7th" rather than "seventh".

Currently extract_number is unable to handle this form regardless of whether the ordinals flag is True or False i.e. the following tests both fail:
```
self.assertEqual(extract_number("this is the 7th test", ordinals=True), 7)
self.assertEqual(extract_number("this is the 7th test", ordinals=False), 7)
```

Ideally this should be handled in the same way as other ordinals to prevent the need to manually extract numbers depending on the STT's output style.

**Comment by JarbasAl** [comment]
this case should work even without the ordinals=True flag, will open a PR for it

**Comment by JarbasAl** [comment]
solved by https://github.com/MycroftAI/lingua-franca/pull/52
