### ISSUE TITLE
Parser and Formatter objects

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/lingua-franca#98]
Should we add Parser and Formatter classes, so that users can instantiate these functions with state?

I can see the utility: instantiate a formatter, specify once that you prefer: commas for decimal points, French for the language, do NOT fall back on English, 24 hour clock.

**Comment by JarbasAl** [comment]
i like this!

using objects is very pythonic

**Comment by ChanceNCounter** [comment]
In fact, it might be helpful for Mycroft skill developers. We'd have to start documenting more thoroughly (which somehow excites me, rather than horrifying me) but Mycroft could just instantiate one parser. Skill authors would wind up doing stuff like, `self.parser.extract_number()`. The library *as such* would still be showcasing itself, as the objects would just be a stateful frontend for the same functions.

Which, come to think of it, even live in "the same place" (`Parser.extract_number() == lingua_franca.parse.extract_number()`

Or Mycroft could just keep doing what it's doing.

**Comment by ChanceNCounter** [comment]
Obviated by the much better solutions in #108 and #128. I tried it as part of the former, and it was lousy.
